### ISSUE TITLE
Circle extraction does not work

### ISSUE THREAD

**Issue by pubguser321** [Schleifinho/pubg-circle-analyzer#19]
Got everything working but when I first extract circles all is good then I try to generate heatmaps, it shows as no telemetry data 
![notele](https://github.com/Schleifinho/pubg-circle-analyzer/assets/168971674/56675f4b-7e70-450d-97f2-231404cf0ac7)

**Comment by pubguser321** [comment]
it's missing assets baltic_main.png etc

**Comment by Schleifinho** [comment]
@pubguser321 you have to create an assets folder and copy the map png there. You can find them on the official pubg assets repo. I didn't include them in the repo because i use the 8k resolution files

Should look like this
![image](https://github.com/Schleifinho/pubg-circle-analyzer/assets/30636595/3fa375ed-92c8-4eda-af4e-e0e4895b7a54)

**Comment by Schleifinho** [comment]
Also there was an issue with creating heatmaps and histograms for esport which i fixed now
